/**
 * Hash Command - Generate hash for text
 */

const crypto = require('crypto');
const config = require('../../config');

module.exports = {
  name: 'hash',
  aliases: ['md5', 'sha256', 'sha512', 'checksum'],
  category: 'utility',
  description: 'Generate hash for text',
  usage: '.hash <algorithm> <text>',
  
  async execute(sock, msg, args, extra) {
    try {
      if (args.length < 2) {
        return extra.reply('❌ Please provide an algorithm and text!\n\n' +
          'Supported algorithms:\n' +
          '• md5\n' +
          '• sha1\n' +
          '• sha256\n' +
          '• sha512\n\n' +
          'Examples:\n' +
          '• .hash md5 Hello World\n' +
          '• .hash sha256 MySecretText');
      }
      
      const algorithm = args[0].toLowerCase();
      const text = args.slice(1).join(' ');
      
      const supportedAlgorithms = ['md5', 'sha1', 'sha256', 'sha512', 'sha224', 'sha384'];
      
      if (!supportedAlgorithms.includes(algorithm)) {
        return extra.reply(`❌ Unsupported algorithm "${algorithm}"\n\nSupported: ${supportedAlgorithms.join(', ')}`);
      }
      
      try {
        const hash = crypto.createHash(algorithm).update(text).digest('hex');
        
        const message = `🔐 *HASH GENERATOR*\n\n` +
                       `📝 Algorithm: ${algorithm.toUpperCase()}\n` +
                       `📄 Input: ${text}\n\n` +
                       `✅ Hash:\n${hash}\n\n` +
                       `_Generated by ${config.botName}_`;
        
        return await extra.reply(message);
        
      } catch (hashError) {
        return await extra.reply('❌ Failed to generate hash. Please try again.');
      }
      
    } catch (error) {
      console.error('Hash command error:', error);
      await extra.reply('❌ Failed to generate hash. Please try again later.');
    }
  }
};