/**
 * Style Command - Generate fancy text styles
 */

const config = require('../../config');

// Text style maps
const styles = {
  bold: {
    map: '𝐚𝐛𝐜𝐝𝐞𝐟𝐠𝐡𝐢𝐣𝐤𝐥𝐦𝐧𝐨𝐩𝐪𝐫𝐬𝐭𝐮𝐯𝐰𝐱𝐲𝐳𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍𝐎𝐏𝐐𝐑𝐒𝐓𝐔𝐕𝐖𝐗𝐘𝐙𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗',
    name: 'Bold'
  },
  italic: {
    map: '𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡0123456789',
    name: 'Italic'
  },
  boldItalic: {
    map: '𝒂𝒃𝒄𝒅𝒆𝒇𝒈𝒉𝒊𝒋𝒌𝒍𝒎𝒏𝒐𝒑𝒒𝒓𝒔𝒕𝒖𝒗𝒘𝒙𝒚𝒛𝑨𝑩𝑪𝑫𝑬𝑭𝑮𝑯𝑰𝑱𝑲𝑳𝒎𝑵𝑶𝑷𝑸𝑹𝑺𝑻𝑼𝑽𝑾𝑿𝒀𝒁𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗',
    name: 'Bold Italic'
  },
  script: {
    map: '𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝑜𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝓂𝒩𝒪𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵',
    name: 'Script'
  },
  fraktur: {
    map: '𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ',
    name: 'Fraktur'
  },
  mono: {
    map: '𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉𝟶𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿',
    name: 'Monospace'
  },
  circled: {
    map: 'ⓐⓑⓒⓓⓔⓕⓖⓗⓘⓙⓚⓛⓜⓝⓞⓟⓠⓡⓢⓣⓤⓥⓦⓧⓨⓩⒶⒷⒸⒹⒺⒻⒼⒽⒾⒿⓀⓁⓂⓃⓄⓅⓆⓇⓈⓉⓊⓋⓌⓍⓎⓏ⓪①②③④⑤⑥⑦⑧⑨',
    name: 'Circled'
  },
  squared: {
    map: '🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉🄰🄱🄲🄳🄴🄵🄶🄷🄸🄹🄺🄻🄼🄽🄾🄿🅀🅁🅂🅃🅄🅅🅆🅇🅈🅉',
    name: 'Squared'
  },
  smallCaps: {
    map: 'ᴀʙᴄᴅᴇғɢʜɪᴊᴋʟᴍɴᴏᴘǫʀsᴛᴜᴠᴡxʏᴢABCDEFGHIJKLMNOPQRSTUVWXYZ',
    name: 'Small Caps'
  },
  wide: {
    map: 'ａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ０１２３４５６７８９',
    name: 'Wide'
  },
  upsideDown: {
    map: 'ɐqɔpǝɟƃɥıɾʞʅɯuodbɹsʇnʌʍxʎzⱯqƆᗡƎℲפHIſꞰ꓁WNOԀQɹS┴∩ΛMX⅄Z0ƖᄅƐㄣϛ9ㄥ86',
    name: 'Upside Down',
    reverse: true
  },
  strikethrough: {
    name: 'Strikethrough',
    chars: true
  }
};

const normalChars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

function convertText(text, style) {
  if (style.chars) {
    // Character-based transformation (like strikethrough)
    if (style.name === 'Strikethrough') {
      return text.split('').map(c => c + '\u0336').join('');
    }
  }
  
  if (!style.map) return text;
  
  let result = '';
  const styleChars = style.map;
  
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    const index = normalChars.indexOf(char);
    
    if (index !== -1 && index < styleChars.length) {
      result += styleChars[index];
    } else {
      result += char;
    }
  }
  
  if (style.reverse) {
    result = result.split('').reverse().join('');
  }
  
  return result;
}

module.exports = {
  name: 'style',
  aliases: ['fancy', 'fancytext', 'textstyle'],
  category: 'utility',
  description: 'Convert text to fancy styles',
  usage: '.style <text>',
  
  async execute(sock, msg, args, extra) {
    try {
      if (args.length === 0) {
        return extra.reply('❌ Please provide text to style!\n\n' +
          'Example: .style Hello World');
      }
      
      const text = args.join(' ');
      
      let message = `✨ *FANCY TEXT STYLES*\n\n`;
      message += `📝 Original: ${text}\n\n`;
      message += `━━━━━━━━━━━━━━━\n\n`;
      
      // Generate all styles
      for (const [key, style] of Object.entries(styles)) {
        const converted = convertText(text, style);
        message += `${style.name}:\n${converted}\n\n`;
      }
      
      message += `━━━━━━━━━━━━━━━\n`;
      message += `_Generated by ${config.botName}_`;
      
      await extra.reply(message);
      
    } catch (error) {
      console.error('Style command error:', error);
      await extra.reply('❌ Failed to generate styles. Please try again.');
    }
  }
};