/**
 * Backup Command - Backup config.js and session info to owner's DM (owner only)
 * Ladybug Bot Mini | by Dev-Ntando
 *
 * Sends the current config.js (with sensitive data masked) and
 * a system snapshot to the owner via private message.
 *
 * Usage: .backup
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const os   = require('os');

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const kb = bytes / 1024;
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  const mb = kb / 1024;
  return `${mb.toFixed(1)} MB`;
}

module.exports = {
  name: 'backup',
  aliases: ['saveconfig', 'configbackup'],
  category: 'owner',
  description: 'Send a system + config snapshot to your DM',
  usage: '.backup',
  ownerOnly: true,
  adminOnly: false,
  groupOnly: false,
  botAdminOnly: false,

  async execute(sock, msg, args, extra) {
    try {
      const config     = require('../../config');
      const configPath = path.join(__dirname, '../../config.js');

      await extra.reply('📦 Preparing backup... Sending to your DM.');

      // ── Build masked config snapshot ─────────────────────
      const ownerJid = Array.isArray(config.ownerNumber)
        ? `${config.ownerNumber[0]}@s.whatsapp.net`
        : `${config.ownerNumber}@s.whatsapp.net`;

      const configSnapshot = {
        botName:      config.botName       || 'N/A',
        prefix:       config.prefix        || '.',
        ownerNumber:  config.ownerNumber   || 'N/A',
        sessionID:    config.sessionID ? config.sessionID.substring(0, 12) + '...[masked]' : 'N/A',
        timezone:     config.timezone      || 'N/A',
        language:     config.language      || 'N/A',
        mode:         config.mode          || 'N/A',
        maintenance:  config.maintenance   ?? false,
        slowmode:     config.slowmode      || 0,
        bannedUsers:  (config.bannedUsers || []).length + ' user(s)',
        autoReact:    config.autoReact     ?? false,
      };

      // ── System info ───────────────────────────────────────
      const uptimeSec = Math.floor(process.uptime());
      const days    = Math.floor(uptimeSec / 86400);
      const hours   = Math.floor((uptimeSec % 86400) / 3600);
      const minutes = Math.floor((uptimeSec % 3600) / 60);
      const uptime  = `${days}d ${hours}h ${minutes}m`;

      const memUsed  = formatBytes(process.memoryUsage().heapUsed);
      const memTotal = formatBytes(os.totalmem());
      const platform = `${os.type()} ${os.arch()}`;
      const nodeVer  = process.version;

      // ── Config file size ─────────────────────────────────
      const configStat = fs.statSync(configPath);
      const configSize = formatBytes(configStat.size);

      const now = new Date().toLocaleString('en-US', {
        timeZone: config.timezone || 'Africa/Harare',
        hour12: false,
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });

      const backupText =
        `╔══════════════════════════╗\n` +
        `║  📦  *BOT BACKUP REPORT*  ║\n` +
        `╚══════════════════════════╝\n\n` +
        `📅 *Date:* ${now}\n` +
        `⏱️ *Uptime:* ${uptime}\n\n` +
        `━━━━━ ⚙️ *Config* ━━━━━\n` +
        Object.entries(configSnapshot)
          .map(([k, v]) => `  • *${k}:* ${v}`)
          .join('\n') +
        `\n  • *config.js size:* ${configSize}\n\n` +
        `━━━━━ 🖥️ *System* ━━━━━\n` +
        `  • *Platform:* ${platform}\n` +
        `  • *Node.js:* ${nodeVer}\n` +
        `  • *RAM Used:* ${memUsed} / ${memTotal}\n\n` +
        `_Backup generated by ${config.botName || 'LadybugBot'}_`;

      // Send to owner's DM
      await sock.sendMessage(ownerJid, { text: backupText });

      // Also confirm in current chat if it was sent from a group
      if (extra.from !== ownerJid) {
        await extra.reply('✅ Backup sent to your DM.');
      }

    } catch (error) {
      console.error('[backup] Error:', error);
      await extra.reply(`❌ Backup failed: ${error.message}`);
    }
  },
};
